# docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mybank_bd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybank
      MYSQL_USER: mybank
      MYSQL_PASSWORD: mybank
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myBank_backend
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://mybank:mybank@db:3306/mybank?serverVersion=8.0&charset=utf8mb4"
    depends_on:
      - db

volumes:
  db_data:
